language: node_js

dist: trusty

node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-installer
      - oracle-java8-set-default

before_install:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - sleep 5

before_script:
  - node_modules/.bin/flow-typed install || echo 'ignored'

script:
  - node_modules/.bin/flow check
  - npm run lint
  - npm test

# after_success:
#   - npm i coveralls && cat test/unit/coverage/lcov.info | coveralls
